# This is a sample config file for the etl process

spark:
  appname: dataverse_etl_sample
  driver:
    memory: 16g
etl:
  - name: data_ingestion___ufl___parquet2ufl
    args:
      input_paths:
        - ./sample/pajama_1G_ufl_1s.parquet
  - name: data_load___huggingface___ufl2hf_obj
