# This is a sample config file for the etl process

spark:
  appname: dataverse_etl_sample
  driver:
    memory: 4g
etl:
  - name: data_ingestion___red_pajama___hf2ufl
    args:
      name_or_path: togethercomputer/RedPajama-Data-1T-Sample
      repartition: 3
  - name: data_load___parquet___ufl
    args:
      save_path: ./sample/pajama_1G_ufl_1s.parquet
