# This is a sample config file for the etl process

spark:
  appname: dataverse_etl_sample
  driver:
    memory: 16g
etl:
  - name: data_ingestion___red_pajama___hf2ufl
  - name: utils___sampling___random
    args:
      sample_n_or_frac: 0.01
  - name: deduplication___polyglot___minhash
  - name: data_load___huggingface___ufl2hf_obj