# This is a sample config file for the etl process

spark:
  appname: dataverse_etl_sample
  driver:
    memory: 4g
etl:
  - name: data_ingestion___red_pajama___hf2ufl
    args:
      name_or_path: togethercomputer/RedPajama-Data-1T-Sample
      split: train
      repartition: 3
